[package]
name = "bevy_mod_fixed"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.12", default-features = false }

[dev-dependencies]
bevy = { version = "0.12", default-features = true }
